version: '3.8'

services:
  db:
    image: postgres:13
    container_name: nest-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestdb
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

volumes:
  pgdata:
